//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ByIdElementLegacyQualificationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementByIdQualificationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementByNameQualificationContract))]
    internal partial class ElementQualificationContract : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ByIdElementLegacyQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class ByIdElementLegacyQualificationContract : Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract
    {
        
        private string ElementNameField;
        
        private System.Guid ElementTypeIdField;
        
        private System.Guid ViewIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ElementName
        {
            get
            {
                return this.ElementNameField;
            }
            set
            {
                this.ElementNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ElementTypeId
        {
            get
            {
                return this.ElementTypeIdField;
            }
            set
            {
                this.ElementTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ViewId
        {
            get
            {
                return this.ViewIdField;
            }
            set
            {
                this.ViewIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementByIdQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class ElementByIdQualificationContract : Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract
    {
        
        private System.Guid ElementIdField;
        
        private System.Guid ViewIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ElementId
        {
            get
            {
                return this.ElementIdField;
            }
            set
            {
                this.ElementIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ViewId
        {
            get
            {
                return this.ViewIdField;
            }
            set
            {
                this.ViewIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementByNameQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class ElementByNameQualificationContract : Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract
    {
        
        private string ElementNameField;
        
        private string ElementTypeNameField;
        
        private string ViewNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ElementName
        {
            get
            {
                return this.ElementNameField;
            }
            set
            {
                this.ElementNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ElementTypeName
        {
            get
            {
                return this.ElementTypeNameField;
            }
            set
            {
                this.ElementTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ViewName
        {
            get
            {
                return this.ViewNameField;
            }
            set
            {
                this.ViewNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionTokenQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class SessionTokenQualificationContract : object
    {
        
        private string DerivedFromField;
        
        private System.Nullable<bool> IncludeMainSessionTokenField;
        
        private System.Nullable<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.RelatedSessionTokenCreationContract> RelatedSessionTokenCreationField;
        
        private string ServiceImplementationGroupNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DerivedFrom
        {
            get
            {
                return this.DerivedFromField;
            }
            set
            {
                this.DerivedFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> IncludeMainSessionToken
        {
            get
            {
                return this.IncludeMainSessionTokenField;
            }
            set
            {
                this.IncludeMainSessionTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.RelatedSessionTokenCreationContract> RelatedSessionTokenCreation
        {
            get
            {
                return this.RelatedSessionTokenCreationField;
            }
            set
            {
                this.RelatedSessionTokenCreationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ServiceImplementationGroupName
        {
            get
            {
                return this.ServiceImplementationGroupNameField;
            }
            set
            {
                this.ServiceImplementationGroupNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedSessionTokenCreationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal enum RelatedSessionTokenCreationContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Upwards = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Downwards = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageByIdQualificationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageByNameQualificationContract))]
    internal partial class SystemUsageQualificationContract : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageByIdQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class SystemUsageByIdQualificationContract : Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract
    {
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageByNameQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class SystemUsageByNameQualificationContract : Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSessionToken", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", ItemName="SessionToken")]
    internal class ArrayOfSessionToken : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementNotFoundFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class ElementNotFoundFaultContract : object
    {
        
        private string NameField;
        
        private System.Nullable<System.Guid> TypeIdField;
        
        private System.Nullable<System.Guid> ViewIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> TypeId
        {
            get
            {
                return this.TypeIdField;
            }
            set
            {
                this.TypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> ViewId
        {
            get
            {
                return this.ViewIdField;
            }
            set
            {
                this.ViewIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageNotFoundFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class SystemUsageNotFoundFaultContract : object
    {
        
        private System.Nullable<System.Guid> IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewNotFoundFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class ViewNotFoundFaultContract : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnhandledFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class UnhandledFaultContract : object
    {
        
        private string IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfImplementationId", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", ItemName="ImplementationId")]
    internal class ArrayOfImplementationId : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionTokensOfServiceImplementationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal partial class SessionTokensOfServiceImplementationContract : object
    {
        
        private string ServiceImplementationIdField;
        
        private Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokensField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ServiceImplementationId
        {
            get
            {
                return this.ServiceImplementationIdField;
            }
            set
            {
                this.ServiceImplementationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens
        {
            get
            {
                return this.SessionTokensField;
            }
            set
            {
                this.SessionTokensField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", ConfigurationName="Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSession" +
        "TokenActivityService")]
    internal interface ICreateSessionTokenActivityService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/Execute", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteEl" +
            "ementNotFoundFaultContractFault", Name="ElementNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteSy" +
            "stemUsageNotFoundFaultContractFault", Name="SystemUsageNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ViewNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteVi" +
            "ewNotFoundFaultContractFault", Name="ViewNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteUn" +
            "handledFaultContractFault", Name="UnhandledFaultContract")]
        Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse Execute(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/Execute", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteRe" +
            "sponse")]
        System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse> ExecuteAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "tem", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "temResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "temUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse CreateSystem(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "tem", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "temResponse")]
        System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse> CreateSystemAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementation", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationElementNotFoundFaultContractFault", Name="ElementNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationSystemUsageNotFoundFaultContractFault", Name="SystemUsageNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ViewNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationViewNotFoundFaultContractFault", Name="ViewNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse CreateByServiceImplementation(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementation", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationResponse")]
        System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse> CreateByServiceImplementationAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokens", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensElementNotFoundFaultContractFault", Name="ElementNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensSystemUsageNotFoundFaultContractFault", Name="SystemUsageNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ViewNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensViewNotFoundFaultContractFault", Name="ViewNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse CreateLeafSessionTokens(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokens", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensResponse")]
        System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse> CreateLeafSessionTokensAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroup", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroupUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse CreateByServiceImplementationGroup(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroup", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroupResponse")]
        System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse> CreateByServiceImplementationGroupAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public System.Nullable<bool> CheckCs20Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=1)]
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract ElementQualification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=2)]
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokenQualificationContract SessionTokenQualification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=3)]
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract SystemUsageQualification;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(System.Nullable<bool> CheckCs20Authorization, Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract ElementQualification, Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokenQualificationContract SessionTokenQualification, Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract SystemUsageQualification)
        {
            this.CheckCs20Authorization = CheckCs20Authorization;
            this.ElementQualification = ElementQualification;
            this.SessionTokenQualification = SessionTokenQualification;
            this.SystemUsageQualification = SystemUsageQualification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken RelatedSessionTokens;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=1)]
        public string SessionToken;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken RelatedSessionTokens, string SessionToken)
        {
            this.RelatedSessionTokens = RelatedSessionTokens;
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSystemRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateSystemRequest
    {
        
        public CreateSystemRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSystemResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateSystemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public string SessionToken;
        
        public CreateSystemResponse()
        {
        }
        
        public CreateSystemResponse(string SessionToken)
        {
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfImplementationId ServiceImplementationIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=1)]
        public string SessionToken;
        
        public CreateByServiceImplementationRequest()
        {
        }
        
        public CreateByServiceImplementationRequest(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfImplementationId ServiceImplementationIds, string SessionToken)
        {
            this.ServiceImplementationIds = ServiceImplementationIds;
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public System.Collections.Generic.List<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokensOfServiceImplementationContract> SessionTokensOfServiceImplementationListe;
        
        public CreateByServiceImplementationResponse()
        {
        }
        
        public CreateByServiceImplementationResponse(System.Collections.Generic.List<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokensOfServiceImplementationContract> SessionTokensOfServiceImplementationListe)
        {
            this.SessionTokensOfServiceImplementationListe = SessionTokensOfServiceImplementationListe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLeafSessionTokensRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateLeafSessionTokensRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public string SessionToken;
        
        public CreateLeafSessionTokensRequest()
        {
        }
        
        public CreateLeafSessionTokensRequest(string SessionToken)
        {
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLeafSessionTokensResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateLeafSessionTokensResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens;
        
        public CreateLeafSessionTokensResponse()
        {
        }
        
        public CreateLeafSessionTokensResponse(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens)
        {
            this.SessionTokens = SessionTokens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationGroupRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationGroupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public string ServiceImplementationGroupName;
        
        public CreateByServiceImplementationGroupRequest()
        {
        }
        
        public CreateByServiceImplementationGroupRequest(string ServiceImplementationGroupName)
        {
            this.ServiceImplementationGroupName = ServiceImplementationGroupName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationGroupResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationGroupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens;
        
        public CreateByServiceImplementationGroupResponse()
        {
        }
        
        public CreateByServiceImplementationGroupResponse(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens)
        {
            this.SessionTokens = SessionTokens;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface ICreateSessionTokenActivityServiceChannel : Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSessionTokenActivityService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class CreateSessionTokenActivityServiceClient : System.ServiceModel.ClientBase<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSessionTokenActivityService>, Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSessionTokenActivityService
    {
        
        public CreateSessionTokenActivityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse Execute(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request)
        {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse> ExecuteAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse CreateSystem(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request)
        {
            return base.Channel.CreateSystem(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse> CreateSystemAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request)
        {
            return base.Channel.CreateSystemAsync(request);
        }
        
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse CreateByServiceImplementation(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request)
        {
            return base.Channel.CreateByServiceImplementation(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse> CreateByServiceImplementationAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request)
        {
            return base.Channel.CreateByServiceImplementationAsync(request);
        }
        
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse CreateLeafSessionTokens(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request)
        {
            return base.Channel.CreateLeafSessionTokens(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse> CreateLeafSessionTokensAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request)
        {
            return base.Channel.CreateLeafSessionTokensAsync(request);
        }
        
        public Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse CreateByServiceImplementationGroup(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request)
        {
            return base.Channel.CreateByServiceImplementationGroup(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse> CreateByServiceImplementationGroupAsync(Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request)
        {
            return base.Channel.CreateByServiceImplementationGroupAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
