//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ByIdElementLegacyQualificationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementByIdQualificationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementByNameQualificationContract))]
    internal partial class ElementQualificationContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ByIdElementLegacyQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class ByIdElementLegacyQualificationContract : CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract {
        
        private string ElementNameField;
        
        private System.Guid ElementTypeIdField;
        
        private System.Guid ViewIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ElementName {
            get {
                return this.ElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNameField, value) != true)) {
                    this.ElementNameField = value;
                    this.RaisePropertyChanged("ElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ElementTypeId {
            get {
                return this.ElementTypeIdField;
            }
            set {
                if ((this.ElementTypeIdField.Equals(value) != true)) {
                    this.ElementTypeIdField = value;
                    this.RaisePropertyChanged("ElementTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ViewId {
            get {
                return this.ViewIdField;
            }
            set {
                if ((this.ViewIdField.Equals(value) != true)) {
                    this.ViewIdField = value;
                    this.RaisePropertyChanged("ViewId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementByIdQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class ElementByIdQualificationContract : CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract {
        
        private System.Guid ElementIdField;
        
        private System.Guid ViewIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ElementId {
            get {
                return this.ElementIdField;
            }
            set {
                if ((this.ElementIdField.Equals(value) != true)) {
                    this.ElementIdField = value;
                    this.RaisePropertyChanged("ElementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid ViewId {
            get {
                return this.ViewIdField;
            }
            set {
                if ((this.ViewIdField.Equals(value) != true)) {
                    this.ViewIdField = value;
                    this.RaisePropertyChanged("ViewId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementByNameQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class ElementByNameQualificationContract : CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract {
        
        private string ElementNameField;
        
        private string ElementTypeNameField;
        
        private string ViewNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ElementName {
            get {
                return this.ElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNameField, value) != true)) {
                    this.ElementNameField = value;
                    this.RaisePropertyChanged("ElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ElementTypeName {
            get {
                return this.ElementTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementTypeNameField, value) != true)) {
                    this.ElementTypeNameField = value;
                    this.RaisePropertyChanged("ElementTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ViewName {
            get {
                return this.ViewNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewNameField, value) != true)) {
                    this.ViewNameField = value;
                    this.RaisePropertyChanged("ViewName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionTokenQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class SessionTokenQualificationContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DerivedFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IncludeMainSessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.RelatedSessionTokenCreationContract> RelatedSessionTokenCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceImplementationGroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DerivedFrom {
            get {
                return this.DerivedFromField;
            }
            set {
                if ((object.ReferenceEquals(this.DerivedFromField, value) != true)) {
                    this.DerivedFromField = value;
                    this.RaisePropertyChanged("DerivedFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> IncludeMainSessionToken {
            get {
                return this.IncludeMainSessionTokenField;
            }
            set {
                if ((this.IncludeMainSessionTokenField.Equals(value) != true)) {
                    this.IncludeMainSessionTokenField = value;
                    this.RaisePropertyChanged("IncludeMainSessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.RelatedSessionTokenCreationContract> RelatedSessionTokenCreation {
            get {
                return this.RelatedSessionTokenCreationField;
            }
            set {
                if ((this.RelatedSessionTokenCreationField.Equals(value) != true)) {
                    this.RelatedSessionTokenCreationField = value;
                    this.RaisePropertyChanged("RelatedSessionTokenCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ServiceImplementationGroupName {
            get {
                return this.ServiceImplementationGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceImplementationGroupNameField, value) != true)) {
                    this.ServiceImplementationGroupNameField = value;
                    this.RaisePropertyChanged("ServiceImplementationGroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedSessionTokenCreationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    internal enum RelatedSessionTokenCreationContract : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Upwards = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Downwards = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageByIdQualificationContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageByNameQualificationContract))]
    internal partial class SystemUsageQualificationContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageByIdQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class SystemUsageByIdQualificationContract : CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract {
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageByNameQualificationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class SystemUsageByNameQualificationContract : CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSessionToken", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", ItemName="SessionToken")]
    [System.SerializableAttribute()]
    internal class ArrayOfSessionToken : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementNotFoundFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class ElementNotFoundFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ViewIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> ViewId {
            get {
                return this.ViewIdField;
            }
            set {
                if ((this.ViewIdField.Equals(value) != true)) {
                    this.ViewIdField = value;
                    this.RaisePropertyChanged("ViewId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUsageNotFoundFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class SystemUsageNotFoundFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewNotFoundFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class ViewNotFoundFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnhandledFaultContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class UnhandledFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfImplementationId", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", ItemName="ImplementationId")]
    [System.SerializableAttribute()]
    internal class ArrayOfImplementationId : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionTokensOfServiceImplementationContract", Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5")]
    [System.SerializableAttribute()]
    internal partial class SessionTokensOfServiceImplementationContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ServiceImplementationIdField;
        
        private CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string ServiceImplementationId {
            get {
                return this.ServiceImplementationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceImplementationIdField, value) != true)) {
                    this.ServiceImplementationIdField = value;
                    this.RaisePropertyChanged("ServiceImplementationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens {
            get {
                return this.SessionTokensField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokensField, value) != true)) {
                    this.SessionTokensField = value;
                    this.RaisePropertyChanged("SessionTokens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", ConfigurationName="Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSession" +
        "TokenActivityService")]
    internal interface ICreateSessionTokenActivityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/Execute", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteEl" +
            "ementNotFoundFaultContractFault", Name="ElementNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteSy" +
            "stemUsageNotFoundFaultContractFault", Name="SystemUsageNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ViewNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteVi" +
            "ewNotFoundFaultContractFault", Name="ViewNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteUn" +
            "handledFaultContractFault", Name="UnhandledFaultContract")]
        CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse Execute(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/Execute", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/ExecuteRe" +
            "sponse")]
        System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse> ExecuteAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "tem", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "temResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "temUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse CreateSystem(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "tem", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateSys" +
            "temResponse")]
        System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse> CreateSystemAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementation", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationElementNotFoundFaultContractFault", Name="ElementNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationSystemUsageNotFoundFaultContractFault", Name="SystemUsageNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ViewNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationViewNotFoundFaultContractFault", Name="ViewNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse CreateByServiceImplementation(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementation", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationResponse")]
        System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse> CreateByServiceImplementationAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokens", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensElementNotFoundFaultContractFault", Name="ElementNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensSystemUsageNotFoundFaultContractFault", Name="SystemUsageNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ViewNotFoundFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensViewNotFoundFaultContractFault", Name="ViewNotFoundFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse CreateLeafSessionTokens(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokens", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateLea" +
            "fSessionTokensResponse")]
        System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse> CreateLeafSessionTokensAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroup", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.UnhandledFaultContract), Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroupUnhandledFaultContractFault", Name="UnhandledFaultContract")]
        CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse CreateByServiceImplementationGroup(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroup", ReplyAction="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5/CreateByS" +
            "erviceImplementationGroupResponse")]
        System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse> CreateByServiceImplementationGroupAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public System.Nullable<bool> CheckCs20Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=1)]
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract ElementQualification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=2)]
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokenQualificationContract SessionTokenQualification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=3)]
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract SystemUsageQualification;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(System.Nullable<bool> CheckCs20Authorization, CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ElementQualificationContract ElementQualification, CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokenQualificationContract SessionTokenQualification, CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SystemUsageQualificationContract SystemUsageQualification) {
            this.CheckCs20Authorization = CheckCs20Authorization;
            this.ElementQualification = ElementQualification;
            this.SessionTokenQualification = SessionTokenQualification;
            this.SystemUsageQualification = SystemUsageQualification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken RelatedSessionTokens;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=1)]
        public string SessionToken;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken RelatedSessionTokens, string SessionToken) {
            this.RelatedSessionTokens = RelatedSessionTokens;
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSystemRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateSystemRequest {
        
        public CreateSystemRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSystemResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateSystemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public string SessionToken;
        
        public CreateSystemResponse() {
        }
        
        public CreateSystemResponse(string SessionToken) {
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfImplementationId ServiceImplementationIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=1)]
        public string SessionToken;
        
        public CreateByServiceImplementationRequest() {
        }
        
        public CreateByServiceImplementationRequest(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfImplementationId ServiceImplementationIds, string SessionToken) {
            this.ServiceImplementationIds = ServiceImplementationIds;
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public System.Collections.Generic.List<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokensOfServiceImplementationContract> SessionTokensOfServiceImplementationListe;
        
        public CreateByServiceImplementationResponse() {
        }
        
        public CreateByServiceImplementationResponse(System.Collections.Generic.List<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.SessionTokensOfServiceImplementationContract> SessionTokensOfServiceImplementationListe) {
            this.SessionTokensOfServiceImplementationListe = SessionTokensOfServiceImplementationListe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLeafSessionTokensRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateLeafSessionTokensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public string SessionToken;
        
        public CreateLeafSessionTokensRequest() {
        }
        
        public CreateLeafSessionTokensRequest(string SessionToken) {
            this.SessionToken = SessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLeafSessionTokensResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateLeafSessionTokensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens;
        
        public CreateLeafSessionTokensResponse() {
        }
        
        public CreateLeafSessionTokensResponse(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens) {
            this.SessionTokens = SessionTokens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationGroupRequest", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public string ServiceImplementationGroupName;
        
        public CreateByServiceImplementationGroupRequest() {
        }
        
        public CreateByServiceImplementationGroupRequest(string ServiceImplementationGroupName) {
            this.ServiceImplementationGroupName = ServiceImplementationGroupName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateByServiceImplementationGroupResponse", WrapperNamespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", IsWrapped=true)]
    internal partial class CreateByServiceImplementationGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService_3.5", Order=0)]
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens;
        
        public CreateByServiceImplementationGroupResponse() {
        }
        
        public CreateByServiceImplementationGroupResponse(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ArrayOfSessionToken SessionTokens) {
            this.SessionTokens = SessionTokens;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ICreateSessionTokenActivityServiceChannel : CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSessionTokenActivityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class CreateSessionTokenActivityServiceClient : System.ServiceModel.ClientBase<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSessionTokenActivityService>, CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ICreateSessionTokenActivityService {
        
        public CreateSessionTokenActivityServiceClient() {
        }
        
        public CreateSessionTokenActivityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateSessionTokenActivityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateSessionTokenActivityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateSessionTokenActivityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse Execute(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteResponse> ExecuteAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse CreateSystem(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request) {
            return base.Channel.CreateSystem(request);
        }
        
        public System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemResponse> CreateSystemAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateSystemRequest request) {
            return base.Channel.CreateSystemAsync(request);
        }
        
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse CreateByServiceImplementation(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request) {
            return base.Channel.CreateByServiceImplementation(request);
        }
        
        public System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationResponse> CreateByServiceImplementationAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationRequest request) {
            return base.Channel.CreateByServiceImplementationAsync(request);
        }
        
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse CreateLeafSessionTokens(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request) {
            return base.Channel.CreateLeafSessionTokens(request);
        }
        
        public System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensResponse> CreateLeafSessionTokensAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateLeafSessionTokensRequest request) {
            return base.Channel.CreateLeafSessionTokensAsync(request);
        }
        
        public CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse CreateByServiceImplementationGroup(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request) {
            return base.Channel.CreateByServiceImplementationGroup(request);
        }
        
        public System.Threading.Tasks.Task<CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupResponse> CreateByServiceImplementationGroupAsync(CallCSServiceFromDotNet4Oidc.Schleupen.CS.PI.SB.Sessions.CreateSessionTokenActivityService.v3_5.CreateByServiceImplementationGroupRequest request) {
            return base.Channel.CreateByServiceImplementationGroupAsync(request);
        }
    }
}
