//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurableAttributesViewContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class ConfigurableAttributesViewContract : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonCriteriaContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonAdvancedCriteriaContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonByIdsCriteriaContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonByKontaktwegIdsCriteriaContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonByPINsCriteriaContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonOneFieldCriteriaContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonSimpleCriteriaContract))]
    internal partial class PersonCriteriaContract : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonAdvancedCriteriaContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonAdvancedCriteriaContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract
    {
        
        private string EMailadresseField;
        
        private System.Nullable<System.DateTime> GeburtsdatumField;
        
        private string GeburtsnameField;
        
        private string HausnummerField;
        
        private string IBANField;
        
        private string NameField;
        
        private string Name2Field;
        
        private string OrtField;
        
        private string PostleitzahlField;
        
        private string RufnummerField;
        
        private string StrasseField;
        
        private string VornameField;
        
        private string Zusatz1Field;
        
        private string Zusatz2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EMailadresse
        {
            get
            {
                return this.EMailadresseField;
            }
            set
            {
                this.EMailadresseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> Geburtsdatum
        {
            get
            {
                return this.GeburtsdatumField;
            }
            set
            {
                this.GeburtsdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Geburtsname
        {
            get
            {
                return this.GeburtsnameField;
            }
            set
            {
                this.GeburtsnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Hausnummer
        {
            get
            {
                return this.HausnummerField;
            }
            set
            {
                this.HausnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name2
        {
            get
            {
                return this.Name2Field;
            }
            set
            {
                this.Name2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Ort
        {
            get
            {
                return this.OrtField;
            }
            set
            {
                this.OrtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Postleitzahl
        {
            get
            {
                return this.PostleitzahlField;
            }
            set
            {
                this.PostleitzahlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Rufnummer
        {
            get
            {
                return this.RufnummerField;
            }
            set
            {
                this.RufnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Strasse
        {
            get
            {
                return this.StrasseField;
            }
            set
            {
                this.StrasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Vorname
        {
            get
            {
                return this.VornameField;
            }
            set
            {
                this.VornameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Zusatz1
        {
            get
            {
                return this.Zusatz1Field;
            }
            set
            {
                this.Zusatz1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Zusatz2
        {
            get
            {
                return this.Zusatz2Field;
            }
            set
            {
                this.Zusatz2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonByIdsCriteriaContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonByIdsCriteriaContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfId IdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfId Ids
        {
            get
            {
                return this.IdsField;
            }
            set
            {
                this.IdsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonByKontaktwegIdsCriteriaContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonByKontaktwegIdsCriteriaContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfId IdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfId Ids
        {
            get
            {
                return this.IdsField;
            }
            set
            {
                this.IdsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonByPINsCriteriaContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonByPINsCriteriaContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfPIN PINsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfPIN PINs
        {
            get
            {
                return this.PINsField;
            }
            set
            {
                this.PINsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonOneFieldCriteriaContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonOneFieldCriteriaContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract
    {
        
        private string SearchValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                this.SearchValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonSimpleCriteriaContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonSimpleCriteriaContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract
    {
        
        private System.Nullable<int> PINField;
        
        private string SearchValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                this.SearchValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfId", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", ItemName="Id")]
    internal class ArrayOfId : System.Collections.Generic.List<System.Guid>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPIN", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", ItemName="PIN")]
    internal class ArrayOfPIN : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDetailContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum PersonDetailContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonIdentitaet = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonIdentitaetAktuell = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonIdentitaetAktuellUndZukunft = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kontaktwege = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Girokonten = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfigurableAttributes = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchModeContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum SearchModeContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exact = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeginsWith = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wildcard = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializedConfigurableAttributesValuesContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class SerializedConfigurableAttributesValuesContract : object
    {
        
        private string SerializedJSONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SerializedJSON
        {
            get
            {
                return this.SerializedJSONField;
            }
            set
            {
                this.SerializedJSONField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChronologySettingsContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class ChronologySettingsContract : object
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologyGranularityContract GranularityField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologyIntervalTypeContract IntervalTypeField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologyKindContract KindField;
        
        private bool PreventClosedTimeboxesField;
        
        private bool PreventMeltingField;
        
        private System.DateTime TerminationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologyGranularityContract Granularity
        {
            get
            {
                return this.GranularityField;
            }
            set
            {
                this.GranularityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologyIntervalTypeContract IntervalType
        {
            get
            {
                return this.IntervalTypeField;
            }
            set
            {
                this.IntervalTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologyKindContract Kind
        {
            get
            {
                return this.KindField;
            }
            set
            {
                this.KindField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool PreventClosedTimeboxes
        {
            get
            {
                return this.PreventClosedTimeboxesField;
            }
            set
            {
                this.PreventClosedTimeboxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool PreventMelting
        {
            get
            {
                return this.PreventMeltingField;
            }
            set
            {
                this.PreventMeltingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.DateTime Termination
        {
            get
            {
                return this.TerminationField;
            }
            set
            {
                this.TerminationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChronologyGranularityContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum ChronologyGranularityContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Day = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hour = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Minute = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Month = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Second = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Year = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChronologyIntervalTypeContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum ChronologyIntervalTypeContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RightOpen = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChronologyKindContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum ChronologyKindContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collection = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ray = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Set = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonContract : object
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.DsgvoZustandContract DsgvoZustandField;
        
        private string ExternalKeyField;
        
        private System.Guid IdField;
        
        private System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegContract> KontaktwegeField;
        
        private System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonIdentitaetContract> PersonIdentitaetenField;
        
        private System.Nullable<int> PINField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SerializedConfigurableAttributesValuesContract SerializedConfigurableAttributesValuesField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.DsgvoZustandContract DsgvoZustand
        {
            get
            {
                return this.DsgvoZustandField;
            }
            set
            {
                this.DsgvoZustandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ExternalKey
        {
            get
            {
                return this.ExternalKeyField;
            }
            set
            {
                this.ExternalKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegContract> Kontaktwege
        {
            get
            {
                return this.KontaktwegeField;
            }
            set
            {
                this.KontaktwegeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonIdentitaetContract> PersonIdentitaeten
        {
            get
            {
                return this.PersonIdentitaetenField;
            }
            set
            {
                this.PersonIdentitaetenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        internal System.Nullable<int> PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                this.PINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SerializedConfigurableAttributesValuesContract SerializedConfigurableAttributesValues
        {
            get
            {
                return this.SerializedConfigurableAttributesValuesField;
            }
            set
            {
                this.SerializedConfigurableAttributesValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        internal int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DsgvoZustandContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum DsgvoZustandContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NichtPseudonymisiert = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pseudonymisiert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Depseudonymisiert = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anonymisiert = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KontaktwegContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.AnschriftContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.EMailContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.GirokontoContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.RufnummerContract))]
    internal partial class KontaktwegContract : object
    {
        
        private string BemerkungField;
        
        private System.Guid IdField;
        
        private System.Nullable<System.Guid> NachfolgerIdField;
        
        private System.Nullable<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegNutzungContract> NutzungField;
        
        private System.DateTime ValidFromField;
        
        private System.Nullable<System.DateTime> ValidToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Bemerkung
        {
            get
            {
                return this.BemerkungField;
            }
            set
            {
                this.BemerkungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> NachfolgerId
        {
            get
            {
                return this.NachfolgerIdField;
            }
            set
            {
                this.NachfolgerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegNutzungContract> Nutzung
        {
            get
            {
                return this.NutzungField;
            }
            set
            {
                this.NutzungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.DateTime ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonIdentitaetContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonIdentitaetContract : object
    {
        
        private System.Nullable<System.Guid> AnredeIdField;
        
        private System.Nullable<System.DateTime> GeburtsdatumField;
        
        private string GeburtsnameField;
        
        private System.Guid IdField;
        
        private string LeitwegIdField;
        
        private string NameField;
        
        private string Name2Field;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.RechtsrolleContract RechtsrolleField;
        
        private string SteuernummerField;
        
        private System.Nullable<System.Guid> TitelIdField;
        
        private string UmsatzssteuerIdField;
        
        private System.DateTime ValidFromField;
        
        private string VornameField;
        
        private string Zusatz1Field;
        
        private string Zusatz2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> AnredeId
        {
            get
            {
                return this.AnredeIdField;
            }
            set
            {
                this.AnredeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> Geburtsdatum
        {
            get
            {
                return this.GeburtsdatumField;
            }
            set
            {
                this.GeburtsdatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Geburtsname
        {
            get
            {
                return this.GeburtsnameField;
            }
            set
            {
                this.GeburtsnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LeitwegId
        {
            get
            {
                return this.LeitwegIdField;
            }
            set
            {
                this.LeitwegIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name2
        {
            get
            {
                return this.Name2Field;
            }
            set
            {
                this.Name2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.RechtsrolleContract Rechtsrolle
        {
            get
            {
                return this.RechtsrolleField;
            }
            set
            {
                this.RechtsrolleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Steuernummer
        {
            get
            {
                return this.SteuernummerField;
            }
            set
            {
                this.SteuernummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> TitelId
        {
            get
            {
                return this.TitelIdField;
            }
            set
            {
                this.TitelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UmsatzssteuerId
        {
            get
            {
                return this.UmsatzssteuerIdField;
            }
            set
            {
                this.UmsatzssteuerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.DateTime ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Vorname
        {
            get
            {
                return this.VornameField;
            }
            set
            {
                this.VornameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Zusatz1
        {
            get
            {
                return this.Zusatz1Field;
            }
            set
            {
                this.Zusatz1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Zusatz2
        {
            get
            {
                return this.Zusatz2Field;
            }
            set
            {
                this.Zusatz2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnschriftContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class AnschriftContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegContract
    {
        
        private string HausnummerField;
        
        private System.Guid LandIdField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.OptInKennzeichenContract OptInKennzeichenField;
        
        private string OrtField;
        
        private string OrtsteilField;
        
        private string PostfachField;
        
        private string PostleitzahlField;
        
        private string StrasseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Hausnummer
        {
            get
            {
                return this.HausnummerField;
            }
            set
            {
                this.HausnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid LandId
        {
            get
            {
                return this.LandIdField;
            }
            set
            {
                this.LandIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.OptInKennzeichenContract OptInKennzeichen
        {
            get
            {
                return this.OptInKennzeichenField;
            }
            set
            {
                this.OptInKennzeichenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Ort
        {
            get
            {
                return this.OrtField;
            }
            set
            {
                this.OrtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Ortsteil
        {
            get
            {
                return this.OrtsteilField;
            }
            set
            {
                this.OrtsteilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Postfach
        {
            get
            {
                return this.PostfachField;
            }
            set
            {
                this.PostfachField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Postleitzahl
        {
            get
            {
                return this.PostleitzahlField;
            }
            set
            {
                this.PostleitzahlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Strasse
        {
            get
            {
                return this.StrasseField;
            }
            set
            {
                this.StrasseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMailContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class EMailContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegContract
    {
        
        private string AdresseField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.OptInKennzeichenContract OptInKennzeichenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Adresse
        {
            get
            {
                return this.AdresseField;
            }
            set
            {
                this.AdresseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.OptInKennzeichenContract OptInKennzeichen
        {
            get
            {
                return this.OptInKennzeichenField;
            }
            set
            {
                this.OptInKennzeichenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GirokontoContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class GirokontoContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegContract
    {
        
        private string IBANField;
        
        private System.Guid KreditinstitutIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid KreditinstitutId
        {
            get
            {
                return this.KreditinstitutIdField;
            }
            set
            {
                this.KreditinstitutIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RufnummerContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class RufnummerContract : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegContract
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.RufnummernArtContract ArtField;
        
        private string NummerField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.OptInKennzeichenContract OptInKennzeichenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.RufnummernArtContract Art
        {
            get
            {
                return this.ArtField;
            }
            set
            {
                this.ArtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Nummer
        {
            get
            {
                return this.NummerField;
            }
            set
            {
                this.NummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.OptInKennzeichenContract OptInKennzeichen
        {
            get
            {
                return this.OptInKennzeichenField;
            }
            set
            {
                this.OptInKennzeichenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KontaktwegNutzungContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum KontaktwegNutzungContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Geschaeftlich = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Privat = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OptInKennzeichenContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class OptInKennzeichenContract : object
    {
        
        private System.Nullable<System.DateTime> GueltigAbField;
        
        private bool OptInField;
        
        private string UserFullNameField;
        
        private System.Nullable<System.Guid> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> GueltigAb
        {
            get
            {
                return this.GueltigAbField;
            }
            set
            {
                this.GueltigAbField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal bool OptIn
        {
            get
            {
                return this.OptInField;
            }
            set
            {
                this.OptInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserFullName
        {
            get
            {
                return this.UserFullNameField;
            }
            set
            {
                this.UserFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.Guid> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RufnummernArtContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum RufnummernArtContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Festnetz = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobiltelefon = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RechtsrolleContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum RechtsrolleContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Natuerlich = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Juristisch = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnhandledFaultContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class UnhandledFaultContract : object
    {
        
        private string IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdempotentOperationPendingFaultContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class IdempotentOperationPendingFaultContract : object
    {
        
        private string IdempotencyKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string IdempotencyKey
        {
            get
            {
                return this.IdempotencyKeyField;
            }
            set
            {
                this.IdempotencyKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaleDataFaultContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class StaleDataFaultContract : object
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfId IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ArrayOfId Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFaultContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class ValidationFaultContract : object
    {
        
        private System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationResultContract> ValidationResultListeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationResultContract> ValidationResultListe
        {
            get
            {
                return this.ValidationResultListeField;
            }
            set
            {
                this.ValidationResultListeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResultContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class ValidationResultContract : object
    {
        
        private System.Guid PersonIdField;
        
        private System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationMessageContract> ValidationMessageListeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationMessageContract> ValidationMessageListe
        {
            get
            {
                return this.ValidationMessageListeField;
            }
            set
            {
                this.ValidationMessageListeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationMessageContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class ValidationMessageContract : object
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonValidationMessageContract PersonValidationMessageField;
        
        private string TextField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationMessageLevelContract ValidationMessageLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonValidationMessageContract PersonValidationMessage
        {
            get
            {
                return this.PersonValidationMessageField;
            }
            set
            {
                this.PersonValidationMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationMessageLevelContract ValidationMessageLevel
        {
            get
            {
                return this.ValidationMessageLevelField;
            }
            set
            {
                this.ValidationMessageLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonValidationMessageContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonValidationMessageContract : object
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegValidationMessageContract KontaktwegValidationMessageField;
        
        private System.Guid PersonIdField;
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonIdentitaetValidationMessageContract PersonIdentitaetValidationMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegValidationMessageContract KontaktwegValidationMessage
        {
            get
            {
                return this.KontaktwegValidationMessageField;
            }
            set
            {
                this.KontaktwegValidationMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonIdentitaetValidationMessageContract PersonIdentitaetValidationMessage
        {
            get
            {
                return this.PersonIdentitaetValidationMessageField;
            }
            set
            {
                this.PersonIdentitaetValidationMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationMessageLevelContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum ValidationMessageLevelContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KontaktwegValidationMessageContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class KontaktwegValidationMessageContract : object
    {
        
        private Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegTypContract KontaktwegTypField;
        
        private System.Guid KontakwegIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.KontaktwegTypContract KontaktwegTyp
        {
            get
            {
                return this.KontaktwegTypField;
            }
            set
            {
                this.KontaktwegTypField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid KontakwegId
        {
            get
            {
                return this.KontakwegIdField;
            }
            set
            {
                this.KontakwegIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonIdentitaetValidationMessageContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal partial class PersonIdentitaetValidationMessageContract : object
    {
        
        private System.Guid PersonIdentitaetIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid PersonIdentitaetId
        {
            get
            {
                return this.PersonIdentitaetIdField;
            }
            set
            {
                this.PersonIdentitaetIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KontaktwegTypContract", Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0")]
    internal enum KontaktwegTypContract : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rufnummer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Girokonto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMail = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anschrift = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", ConfigurationName="Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.IPersonEntityService")]
    internal interface IPersonEntityService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/Query", ReplyAction="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.UnhandledFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/QueryUnhandledFaultCont" +
            "ractFault", Name="UnhandledFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.IdempotentOperationPendingFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/QueryIdempotentOperatio" +
            "nPendingFaultContractFault", Name="IdempotentOperationPendingFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.StaleDataFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/QueryStaleDataFaultCont" +
            "ractFault", Name="StaleDataFaultContract")]
        Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryResponse Query(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/Query", ReplyAction="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/QueryResponse")]
        System.Threading.Tasks.Task<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryResponse> QueryAsync(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChanges", ReplyAction="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChangesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChangesValidationFa" +
            "ultContractFault", Name="ValidationFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.UnhandledFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChangesUnhandledFau" +
            "ltContractFault", Name="UnhandledFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.IdempotentOperationPendingFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChangesIdempotentOp" +
            "erationPendingFaultContractFault", Name="IdempotentOperationPendingFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.StaleDataFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChangesStaleDataFau" +
            "ltContractFault", Name="StaleDataFaultContract")]
        Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesResponse SaveChanges(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChanges", ReplyAction="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/SaveChangesResponse")]
        System.Threading.Tasks.Task<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesResponse> SaveChangesAsync(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/Validate", ReplyAction="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/ValidateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/ValidateValidationFault" +
            "ContractFault", Name="ValidationFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.UnhandledFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/ValidateUnhandledFaultC" +
            "ontractFault", Name="UnhandledFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.IdempotentOperationPendingFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/ValidateIdempotentOpera" +
            "tionPendingFaultContractFault", Name="IdempotentOperationPendingFaultContract")]
        [System.ServiceModel.FaultContractAttribute(typeof(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.StaleDataFaultContract), Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/ValidateStaleDataFaultC" +
            "ontractFault", Name="StaleDataFaultContract")]
        Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateResponse Validate(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/Validate", ReplyAction="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0/ValidateResponse")]
        System.Threading.Tasks.Task<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateResponse> ValidateAsync(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRequest", WrapperNamespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", IsWrapped=true)]
    internal partial class QueryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://Schleupen.CS.PI.SB.Broker_3.2")]
        public string SessionToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://Schleupen.CS.PI.SB.Idempotency_3.0")]
        public string IdempotencyKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=0)]
        public string ConfigurableAttributesContainer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=1)]
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ConfigurableAttributesViewContract ConfigurableAttributesView;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=2)]
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract Criteria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=3)]
        public System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonDetailContract> Details;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=4)]
        public System.Nullable<int> MaxResults;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=5)]
        public System.Nullable<System.Guid> RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=6)]
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SearchModeContract SearchMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=7)]
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SerializedConfigurableAttributesValuesContract SerializedConfigurableAttributesValues;
        
        public QueryRequest()
        {
        }
        
        public QueryRequest(string SessionToken, string IdempotencyKey, string ConfigurableAttributesContainer, Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ConfigurableAttributesViewContract ConfigurableAttributesView, Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonCriteriaContract Criteria, System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonDetailContract> Details, System.Nullable<int> MaxResults, System.Nullable<System.Guid> RequestId, Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SearchModeContract SearchMode, Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SerializedConfigurableAttributesValuesContract SerializedConfigurableAttributesValues)
        {
            this.SessionToken = SessionToken;
            this.IdempotencyKey = IdempotencyKey;
            this.ConfigurableAttributesContainer = ConfigurableAttributesContainer;
            this.ConfigurableAttributesView = ConfigurableAttributesView;
            this.Criteria = Criteria;
            this.Details = Details;
            this.MaxResults = MaxResults;
            this.RequestId = RequestId;
            this.SearchMode = SearchMode;
            this.SerializedConfigurableAttributesValues = SerializedConfigurableAttributesValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryResponse", WrapperNamespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", IsWrapped=true)]
    internal partial class QueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=0)]
        public string ConfigurableAttributesContainer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=1)]
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologySettingsContract KontaktwegChronologySettings;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=2)]
        public System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=3)]
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologySettingsContract PersonIdentitaetChronologySettings;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=4)]
        public System.Nullable<System.Guid> RequestId;
        
        public QueryResponse()
        {
        }
        
        public QueryResponse(string ConfigurableAttributesContainer, Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologySettingsContract KontaktwegChronologySettings, System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen, Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ChronologySettingsContract PersonIdentitaetChronologySettings, System.Nullable<System.Guid> RequestId)
        {
            this.ConfigurableAttributesContainer = ConfigurableAttributesContainer;
            this.KontaktwegChronologySettings = KontaktwegChronologySettings;
            this.Personen = Personen;
            this.PersonIdentitaetChronologySettings = PersonIdentitaetChronologySettings;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveChangesRequest", WrapperNamespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", IsWrapped=true)]
    internal partial class SaveChangesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://Schleupen.CS.PI.SB.Broker_3.2")]
        public string SessionToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://Schleupen.CS.PI.SB.Idempotency_3.0")]
        public string IdempotencyKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=0)]
        public string ConfigurableAttributesContainer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=1)]
        public System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=2)]
        public System.Nullable<System.Guid> RequestId;
        
        public SaveChangesRequest()
        {
        }
        
        public SaveChangesRequest(string SessionToken, string IdempotencyKey, string ConfigurableAttributesContainer, System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen, System.Nullable<System.Guid> RequestId)
        {
            this.SessionToken = SessionToken;
            this.IdempotencyKey = IdempotencyKey;
            this.ConfigurableAttributesContainer = ConfigurableAttributesContainer;
            this.Personen = Personen;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveChangesResponse", WrapperNamespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", IsWrapped=true)]
    internal partial class SaveChangesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=0)]
        public System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=1)]
        public System.Nullable<System.Guid> RequestId;
        
        public SaveChangesResponse()
        {
        }
        
        public SaveChangesResponse(System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen, System.Nullable<System.Guid> RequestId)
        {
            this.Personen = Personen;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateRequest", WrapperNamespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", IsWrapped=true)]
    internal partial class ValidateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://Schleupen.CS.PI.SB.Broker_3.2")]
        public string SessionToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://Schleupen.CS.PI.SB.Idempotency_3.0")]
        public string IdempotencyKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=0)]
        public System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=1)]
        public System.Nullable<System.Guid> RequestId;
        
        public ValidateRequest()
        {
        }
        
        public ValidateRequest(string SessionToken, string IdempotencyKey, System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.PersonContract> Personen, System.Nullable<System.Guid> RequestId)
        {
            this.SessionToken = SessionToken;
            this.IdempotencyKey = IdempotencyKey;
            this.Personen = Personen;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateResponse", WrapperNamespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", IsWrapped=true)]
    internal partial class ValidateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=0)]
        public System.Nullable<System.Guid> RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://Schleupen.CS.AP.ZD.Personen.PersonEntityService_3.0", Order=1)]
        public System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationResultContract> ValidationResultListe;
        
        public ValidateResponse()
        {
        }
        
        public ValidateResponse(System.Nullable<System.Guid> RequestId, System.Collections.Generic.List<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidationResultContract> ValidationResultListe)
        {
            this.RequestId = RequestId;
            this.ValidationResultListe = ValidationResultListe;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface IPersonEntityServiceChannel : Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.IPersonEntityService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class PersonEntityServiceClient : System.ServiceModel.ClientBase<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.IPersonEntityService>, Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.IPersonEntityService
    {
        
        public PersonEntityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryResponse Query(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryRequest request)
        {
            return base.Channel.Query(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryResponse> QueryAsync(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.QueryRequest request)
        {
            return base.Channel.QueryAsync(request);
        }
        
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesResponse SaveChanges(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesRequest request)
        {
            return base.Channel.SaveChanges(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesResponse> SaveChangesAsync(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.SaveChangesRequest request)
        {
            return base.Channel.SaveChangesAsync(request);
        }
        
        public Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateResponse Validate(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateRequest request)
        {
            return base.Channel.Validate(request);
        }
        
        public System.Threading.Tasks.Task<Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateResponse> ValidateAsync(Schleupen.CS.AP.ZD.Personen.PersonEntityService.v3_0.ValidateRequest request)
        {
            return base.Channel.ValidateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
